version: "3.8"

services:
    web:
        image: hm-web
        build: ./web
        restart: always
        depends_on:
            - db
        ports:
            - 50080:80
        networks:
            - web-db
        volumes:
            - .\web:/var/www/html/
        env_file:
            - ./db/database_least_privileged_users.env
        environment:
            - TZ=CET

    db:
        image: hm-db
        build: ./db
        restart: always
        command: mysqld --default-authentication-plugin=mysql_native_password --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
        networks:
            - web-db
            - admin-db
        volumes:
            - houses-clients:/var/lib/mysql
        secrets:
            - db_root_password
            - db_database
        environment:
            - TZ=CET
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
            - MYSQL_DATABASE_FILE=/run/secrets/db_database

    phpmyadmin:
        image: phpmyadmin:5.0-apache
        depends_on:
            - db
        ports:
            - 51080:80
        networks:
            - admin-db
        secrets:
            - db_root_password
        environment:
            - TZ=CET
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD_FILE=/run/secrets/db_root_password

    databacker:
        image: databack/mysql-backup
        depends_on:
            - db
        restart: always
        networks:
            - admin-db
        env_file:
            - ./db/secrets/databacker.env
        environment:
            - DB_DUMP_FREQ=1440
            - DB_DUMP_BEGIN=+1
            - DB_DUMP_DEBUG=true
            - DB_DUMP_SAFECHARS=true
        volumes:
            - ./db/backups:/backup

networks:
    web-db:
    admin-db:

volumes:
    houses-clients:

secrets:
    db_root_password:
        file: ./db/secrets/root_password
    db_database:
        file: ./db/secrets/database
